export const tasks = [

  {
    id: 1,
    status: 'Без статуса',
    title: 'Web Design',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 2,
    status: 'Без статуса',
    title: 'Web Design',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 3,
    status: 'Без статуса',
    title: 'Copywriting',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 4,
    status: 'Нужно сделать',
    title: 'Research',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 5,
    status: 'Нужно сделать',
    title: 'Web Design',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 6,
    status: 'В работе',
    title: 'Copywriting',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 7,
    status: 'Готово',
    title: 'Web Design',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 8,
    status: 'Тестирование',
    title: 'Web Design',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
  {
    id: 9,
    status: 'Тестирование',
    title: 'Copywriting',
    taskName: 'Название задачи',
    date: '30.10.23',
  },
];
